USE [master]
GO

/****** Object:  Database [DroneTaxi]    Script Date: 31.07.2020 8:08:41 ******/
CREATE DATABASE [DroneTaxi]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DroneTaxi', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DroneTaxi.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DroneTaxi_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DroneTaxi_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DroneTaxi].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DroneTaxi] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DroneTaxi] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DroneTaxi] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DroneTaxi] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DroneTaxi] SET ARITHABORT OFF 
GO

ALTER DATABASE [DroneTaxi] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DroneTaxi] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DroneTaxi] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DroneTaxi] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DroneTaxi] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DroneTaxi] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DroneTaxi] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DroneTaxi] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DroneTaxi] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DroneTaxi] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DroneTaxi] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DroneTaxi] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DroneTaxi] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DroneTaxi] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DroneTaxi] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DroneTaxi] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DroneTaxi] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DroneTaxi] SET RECOVERY FULL 
GO

ALTER DATABASE [DroneTaxi] SET  MULTI_USER 
GO

ALTER DATABASE [DroneTaxi] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DroneTaxi] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DroneTaxi] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DroneTaxi] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DroneTaxi] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DroneTaxi] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DroneTaxi] SET  READ_WRITE 
GO


USE [DroneTaxi]
GO

/****** Object:  Table [dbo].[Role]    Script Date: 31.07.2020 8:10:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Role](
	[Role_NUM] [int] NOT NULL,
	[Role_Name] [varchar](max) NOT NULL,
	[Role_ID] [varchar](10) NOT NULL,
 CONSTRAINT [PK_Role] PRIMARY KEY CLUSTERED 
(
	[Role_NUM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


USE [DroneTaxi]
GO

/****** Object:  Table [dbo].[Users]    Script Date: 31.07.2020 8:11:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Users](
	[Email] [nvarchar](100) NOT NULL,
	[Password] [nvarchar](100) NOT NULL,
	[FirstName] [nvarchar](80) NULL,
	[MiddleName] [nvarchar](80) NULL,
	[LastName] [nvarchar](80) NULL,
	[RoleId] [varchar](10) NOT NULL,
	[Phone] [nvarchar](11) NULL,
	[Gender] [nchar](1) NOT NULL,
	[DateOfBirth] [date] NULL,
	[ProfileImage] [image] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[Users]  WITH CHECK ADD  CONSTRAINT [FK_Users_Role] FOREIGN KEY([RoleId])
REFERENCES [dbo].[Role] ([Role_ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Users] CHECK CONSTRAINT [FK_Users_Role]
GO
